#!/bin/sh
export TELESCOPE_PATH="$APPDIR/usr/bin"
export OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$OLD_LD_LIBRARY_PATH"
export STARDUST_THEMES="$APPDIR/usr/share"

$TELESCOPE_PATH/stardust-xr-server -o 6 -e "$TELESCOPE_PATH/startup_script" "$@"
